const playlist = [
  {
    artist: 'Rob_Bailey_and_the_Hustle_Standard',
    title: 'Run_this',
    track: 'rob_bailey_and_the_hustle_standard_-_run_this',
    image: 'Rob Bailey - Run This',
  },
  {
    artist: 'The_Siege',
    title: 'The_Siege_-_Outside',
    track: 'The_Siege_-_Outside',
    image: 'The Seige - Outside',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Savage',
    track: 'NEFFEX_-_Savage',
    image: 'Neffex - Savage',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Careless',
    track: 'NEFFEX_-_Careless',
    image: 'Neffex - Careless',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Life',
    track: 'NEFFEX_-_Life',
    image: 'Neffex - Life',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Play',
    track: 'NEFFEX_-_Play',
    image: 'Neffex - Play',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Rumors',
    track: 'NEFFEX_-_Rumors',
    image: 'Neffex - Rumors',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Soldier',
    track: 'NEFFEX_-_Soldier',
    image: 'Neffex - Soldier',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Struggle',
    track: 'NEFFEX_-_Struggle',
    image: 'Neffex - Struggle',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Unstoppable',
    track: 'NEFFEX_-_Unstoppable',
    image: 'Neffex - Unstoppable',
  },
  {
    artist: 'Okean Elzi',
    title: 'Okean Elzi - Na nebi',
    track: 'Okean Elzi - Na nebi',
    image: 'Okean Elzy - In the sky',
  },
  {
    artist: 'ICIQ',
    title: 'ICIQ - Pokidayu',
    track: 'ICIQ - Pokidayu',
    image: 'ICIQ - Pokidayu',
  },
  {
    artist: 'Skofka',
    title: 'Skofka_-_Oy_Na_Oy',
    track: 'Skofka_-_Oy_Na_Oy',
    image: 'Skoffka - oy na oy',
  },
  {
    artist: 'Neffex',
    title: 'NEFFEX_-_Best_of_Me',
    track: 'NEFFEX_-_Best_of_Me',
    image: 'Neffex - Best of me',
  },
];
